const columnsForClients = [
  {
    name: "id",
    required: true,
    label: "ID",
    align: "left",
    field: (row) => row.id,
    format: (val) => `${val}`, // format of sort
    sortable: true,
  },
  {
    name: "name",
    required: true,
    label: "Nombre",
    align: "left",
    field: (row) => row.name,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "email",
    required: true,
    label: "E-Mail",
    align: "left",
    field: (row) => row.email,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "celular",
    required: true,
    label: "Celular",
    align: "left",
    field: (row) => row.celular,
    sortable: true,
  },
];

const columnsForAuthors = [
  {
    name: "id",
    required: true,
    label: "ID",
    align: "left",
    field: (row) => row.id,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "name",
    required: true,
    label: "Nombre",
    align: "left",
    field: (row) => row.name,
    format: (val) => `${val}`,
    sortable: true,
  },
];

const columsnForBooks = [
  {
    name: "id",
    required: true,
    label: "ID",
    align: "left",
    field: (row) => row.id,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "titulo",
    required: true,
    label: "Titulo",
    align: "left",
    field: (row) => row.titulo,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "nombre_autor",
    required: true,
    label: "Nombre Autor",
    align: "left",
    field: (row) => row.nombre_autor,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "lote",
    required: true,
    label: "lote",
    align: "left",
    field: (row) => row.lote,
    format: (val) => `${val}`,
    sortable: true,
  },
];

const columnsForLoans = [
  {
    name: "id",
    required: true,
    label: "ID",
    align: "left",
    field: (row) => row.id,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "titulo_libro",
    required: true,
    label: "Nombre Libro",
    align: "left",
    field: (row) => row.nombre_libro,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "nombre_cliente",
    required: true,
    label: "Nombre Cliente",
    align: "left",
    field: (row) => row.nombre_cliente,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "fecha_prestamo",
    required: true,
    label: "Fecha de Prestamo",
    align: "left",
    field: (row) => row.fecha_prestamo,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "dias_prestamo",
    required: true,
    label: "Dias Prestamo",
    align: "left",
    field: (row) => row.dias_prestamo,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "estado",
    required: true,
    label: "Estado",
    align: "left",
    field: (row) => row.estado,
    format: (val) => `${val}`,
    sortable: true,
  },
];

export {
  columnsForAuthors,
  columnsForClients,
  columsnForBooks,
  columnsForLoans,
};
